apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pgroonga.yaml
- brigadasos-db.yaml
- pgsync.yaml
namespace: nadelog
images:
- name: nadelog
  newName: ghcr.io/brigadasos/nadelog
  newTag: v0.0.2-1
