apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nadelog-backend.yaml
namespace: nadelog
images:
- name: nadelog-backend
  newName: ghcr.io/brigadasos/nadelog
  newTag: v0.0.2-1
